### ISSUE TITLE
Initialize a blank django project

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/College-Application-BE#1]
## Goal
Initialize a blank Django project.

### Tasks
- [x] Initialize a Django project
- [x] Initialize `Pipenv`
- [x] Connect it to a MySQL backend
- [x] Add and install a new `shared` app to hold common functionalities and models.
- [x] Add and install a new `accounts` 
- [x] Add a new `CustomUser` model inside the accounts app and use it to replace the default user. Add `profile` model with a signal to attach it to the `CustomUser` model.
- [x] Install and add DRF (Django REST framework).
- [x] Install and add `django-authtools` to replace `email` as a `username`.
- [x] Install and add `django-extensions` for debugging purpose.
- [x] Initialize `travis` by adding `.travis.yml` configuration file.
