### ISSUE TITLE
Add endpoints for users to create, retrieve, update and delete an application 

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/College-Application-BE#11]
# Goal
Add endpoints where authenticated users can use to create , retrieve , update and delete program application instances.

## Tasks

- [ ] Create `ApplicationSerializer` for serializing an `Application` model instance. 

- [ ] Add an endpoint for creating, retrieving, updating and deleting applications. Use `viewsets` to create the endpoints. The endpoint should be placed at `/programs/applications/`.

- [ ] Add tests for the endpoints.

**Notes:**

1. Only authenticated users can acces the endpoints.
2. Users can only retrieve, update or delete applications they own.
