### ISSUE TITLE
Init a new app called `programs`

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/College-Application-BE#3]
# Goal
Initialize a new Django app called `programs` that will manage a list of College (University) programs that the student can apply too.

## Tasks
- [x] Initialize and add an app called `programs`.
- [x] Add a URL programs `/programs/`
- [x] Add the following models:  `College`, `Program`, `Requirement` `Application`

**Note**: The fields and attributes of the models is provided below.

### 1. College
Field | Type | Required | Remark
----- | ------ | -------- | ---------
id | UUIDField | Yes |  -
name | CharField | Yes |  -
short_name | CharField | Yes |  Abbrevation of the College
summary | TextField | No |  -
country | CharField | Yes |  -
city | CharField | No |  -
link | URLField | Yes |  -

### 2. Program
Field | Type | Required | Remark
----- | ------ | -------- | ---------
id | UUIDField | Yes |  -
college | ForeignKey | Yes | -
title | CharField | Yes |  -
degree_type | CharField | Yes |  Choices (Bachelor, Masters, PhD)
summary | TextField | No |  -
course_start_date | DateField | No | -
application_start_date | DateField | Yes | -
application_end_date | DateField | Yes | -
link | URLField | Yes |  -
created_at | DateTimeField | Yes | -
updated_at | DateTimeField | Yes | - 

### 3. Requirement
Field | Type | Required | Remark
----- | ------ | -------- | ---------
id | UUIDField | Yes |  -
program | ForeignKey | Yes | -
name | CharField | Yes |  -
description | TextField | No |  -
is_optional | BooleanField | Yes | -
link | URLField | No |  -
created_at | DateTimeField | Yes | -
updated_at | DateTimeField | Yes | - 

### 4. Application
Field | Type | Required | Remark
----- | ------ | -------- | ---------
id | UUIDField | Yes |  -
user | ForeignKey | Yes | -
program | ForeignKey | Yes | -
completed_requirements | ManyToManyField | No | -
status | CharField | Yes |  Choices (`In Progress`, `Submitted`, `Accepted`, `Rejected`)
link | URLField | No |  -
created_at | DateTimeField | Yes | This could be a link to an online form if the application requires the user to fill one. 
updated_at | DateTimeField | Yes | -
