### ISSUE TITLE
Add endpoint to retrieve colleges

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/College-Application-BE#5]
# Goal
Add endpoints to retrieve a `list` and `details` of colleges. 

## Tasks
- [x] Create a serializer for serializing a `College` model instance. 
- [x] Add an endpoint for retrieving a list of colleges instances. The endpoint should be placed at `/programs/colleges/`. 
- [x] Add an endpoint for retrieving details of a college instance. The endpoint should be placed at `/programs/colleges/<id>/`. 
- [ ] Add tests for the endpoints.
