### ISSUE TITLE
Add endpoints to retrieve `list` and `details` of program instances 

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/College-Application-BE#6]
# Goal
Add endpoints for retrieving `list` and `details` of college program instances.

## Tasks

- [ ] Create `ProgramSerializer` for serializing a `Program` model instance. The serializer should include the list of related `requirements`. 

- [ ] Add an endpoint for retrieving a list of  program instance. The endpoint should be placed at `/programs/programs/`. 

- [ ] Add an endpoint for retrieving details of a program instance. The endpoint should be placed at `/programs/programs/<id>/`. 

- [ ] Add tests for the endpoints.
