### ISSUE TITLE
Add an endpoint for retrieving `details` of requirement instances 

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/College-Application-BE#7]
# Goal
Add an endpoint for retrieving `details` of a `requirement` instance.

## Tasks

- [ ] Add `RequirementSerializer` to serialize a `Requirement` model instance.

- [ ] Add an endpoint to retrieve a single `requirement` instance. The endpoint should be placed at `/programs/requirements/<id>/` URL path.

- [ ] Add tests for the endpoint.
